// Product categories based on medicalinst.net structure
export const PRODUCT_CATEGORIES = {
  dental: {
    name: "Dental Instruments",
    slug: "dental-instruments",
    icon: "FaTooth",
    color: "from-red-600 to-red-800",
    subcategories: [
      { id: "apical-fragment-ejectors", name: "Apical Fragment Ejectors", slug: "apical-fragment-ejectors" },
      { id: "applicator-amalgam-carriers", name: "Applicator and Amalgam Carriers", slug: "applicator-and-amalgam-carriers" },
      { id: "articulators", name: "Articulators", slug: "articulators" },
      { id: "blacks-cutting-instruments", name: "Black's Cutting Instruments", slug: "blacks-cutting-instruments" },
      { id: "bone-curettes", name: "Bone Curettes", slug: "bone-curettes" },
      { id: "bone-files", name: "Bone Files", slug: "bone-files" },
      { id: "bone-rongeurs", name: "Bone Rongeurs", slug: "bone-rongeurs" },
      { id: "calibrated-probes", name: "Calibrated Probes", slug: "calibrated-probes" },
      { id: "caliper-rulers", name: "Caliper Rulers", slug: "caliper-rulers" },
      { id: "cavity-preparation", name: "Cavity Preparation", slug: "cavity-preparation" },
      { id: "cement-mixing-spatulas", name: "Cement & Mixing Spatulas", slug: "cement-mixing-spatulas" },
      { id: "chisels-gouges", name: "Chisels and Gouges", slug: "chisels-and-gouges" },
      { id: "cotton-plier-dressing-tweezers", name: "Cotton Plier & Dressing Tweezers", slug: "cotton-plier-dressing-tweezers" },
      { id: "crown-removers", name: "Crown Removers", slug: "crown-removers" },
      { id: "dental-syringes", name: "Dental Syringes", slug: "dental-syringes" },
      { id: "endodontic-instruments", name: "Endodontic Instruments", slug: "endodontic-instruments" },
      { id: "excavators", name: "Excavators", slug: "excavators" },
      { id: "filling-instruments", name: "Filling Instruments", slug: "filling-instruments" },
      { id: "forceps-for-children", name: "Forceps For Children", slug: "forceps-for-children" },
      { id: "gracey-curettes", name: "Gracey Curettes", slug: "gracey-curettes" },
      { id: "gum-scissors", name: "Gum Scissors", slug: "gum-scissors" },
      { id: "haemostatic-forceps", name: "Haemostatic Forceps", slug: "haemostatic-forceps-dental-instruments" },
      { id: "impression-trays", name: "Impression Trays Stainless Steel", slug: "impression-trays-stainless-steel" },
      { id: "matrix-retainers", name: "Matrix Retainers", slug: "matrix-retainers" },
      { id: "miscellaneous-dental", name: "Miscellaneous Products", slug: "miscellaneous-products" },
      { id: "mixing-separating-spatulas", name: "Mixing & Separating Spatulas", slug: "mixing-separating-spatulas" },
      { id: "mouth-gags-retractor", name: "Mouth Gags & Retractor", slug: "mouth-gags-retractor" },
      { id: "needle-holders-dental", name: "Needle Holders", slug: "needle-holders" },
      { id: "operating-scissors-dental", name: "Operating Scissors", slug: "operating-scissors" },
      { id: "orthodontic-instruments", name: "Orthodontic Instruments", slug: "orthodontic-instruments" },
      { id: "periodontia-instruments", name: "Periodontia Instruments", slug: "periodontia-instruments" },
      { id: "pertotomes-papilla-elevators", name: "Pertotomes and Papilla Elevators", slug: "pertotomes-and-papilla-elevators" },
      { id: "plastic-filling-instruments", name: "Plastic Filling Instruments", slug: "plastic-filling-instruments" },
      { id: "plastic-filling-excavators", name: "Plastic Filling Instruments and Excavators", slug: "plastic-filling-instruments-and-excavators" },
      { id: "pliers-orthodontics-prosthetics", name: "Pliers For Orthodontics & Prosthetics", slug: "pliers-for-orthodontics-prosthetics" },
      { id: "pliers-mixing-sp-knives", name: "Pliers Mixing Spatulas and Plaster Cutting Knives", slug: "pliers-mixing-spatulas-and-plaster-cutting-knives" },
      { id: "probes-explorers", name: "Probes & Explorers", slug: "probes-explorers" },
      { id: "probes-single-end", name: "Probes Single End", slug: "probes-single-end" },
      { id: "root-elevators", name: "Root Elevators", slug: "root-elevators" },
      { id: "root-splinter-forceps", name: "Root Splinter Forceps", slug: "root-splinter-forceps" },
      { id: "rubber-dam-punch-clamp-forceps", name: "Rubber Dam Punch and Clamp Forceps", slug: "rubber-dam-punch-and-clamp-forceps" },
      { id: "scalers", name: "Scalers", slug: "scalers" },
      { id: "spreaders", name: "Spreaders", slug: "spreaders" },
      { id: "tooth-extracting-forceps-american", name: "Tooth Extracting Forceps (American)", slug: "tooth-extracting-forceps-american" },
      { id: "tooth-extracting-forceps-british", name: "Tooth Extracting Forceps (British)", slug: "tooth-extracting-forceps-british" },
      { id: "universal-curettes", name: "Universal Curettes", slug: "universal-curettes" },
      { id: "wax-modelling-carvers", name: "Wax and Modelling Carvers", slug: "wax-and-modelling-carvers" },
      { id: "wax-knives-bone-files-curettes", name: "Wax Knives Bone Files and Curettes", slug: "wax-knives-bone-files-and-curettes" },
      { id: "wisdom-extracting-forceps", name: "Wisdom Extracting Forceps", slug: "wisdom-extracting-forceps" },
    ]
  },
  surgical: {
    name: "Surgical Instruments",
    slug: "surgical-instruments",
    icon: "FaHammer",
    color: "from-red-600 to-red-800",
    subcategories: [
      { id: "orthopedic", name: "Orthopedic", slug: "orthopedic" },
      { id: "plastic-surgery-instruments", name: "Plastic Surgery Instruments", slug: "plastic-surgery-instruments" },
      { id: "minor-surgery-sets-kits", name: "Minor Surgery Instruments Sets and Kits", slug: "minor-surgery-instruments-sets-and-kits" },
      { id: "miscellaneous-surgical", name: "Miscellaneous Products", slug: "miscellaneous-products-surgical-instruments" },
      { id: "ophthalmic-instruments-surgical", name: "Ophthalmic Instruments", slug: "ophthalmic-instruments" },
      { id: "anaesthesia", name: "Anaesthesia", slug: "anaesthesia" },
      { id: "artery-forceps", name: "Artery Forceps", slug: "artery-forceps" },
      { id: "asepsis", name: "Asepsis", slug: "asepsis" },
      { id: "bone-surgery-1", name: "Bone Surgery (Part 1)", slug: "bone-surgery-part-1" },
      { id: "bone-surgery-2", name: "Bone Surgery (Part 2)", slug: "bone-surgery-part-2" },
      { id: "cardiovascular", name: "Cardiovascular", slug: "cardiovascular" },
      { id: "cotton-swab-forceps", name: "Cotton Swab Forceps", slug: "cotton-swab-forceps" },
      { id: "dermatology", name: "Dermatology", slug: "dermatology" },
      { id: "diagnostics", name: "Diagnostics", slug: "diagnostics" },
      { id: "dressing-sponge-forceps", name: "Dressing & Sponge Forceps", slug: "dressing-sponge-forceps" },
      { id: "dressing-tissue-forceps", name: "Dressing & Tissue Forceps", slug: "dressing-tissue-forceps" },
      { id: "gall-bladder", name: "Gall Bladder", slug: "gall-bladder" },
      { id: "gynecology-surgical", name: "Gynecology", slug: "gynecology" },
      { id: "intestinal-stomach", name: "Intestinal & Stomach", slug: "intestinal-stomach" },
      { id: "maxillo-facial", name: "Maxillo-Facial", slug: "maxillo-facial" },
      { id: "neuro-surgery", name: "Neuro Surgery", slug: "neuro-surgery" },
      { id: "obstetrics", name: "Obstetrics", slug: "obstetrics" },
      { id: "ophthalmology", name: "Ophthalmology", slug: "ophthalmology" },
      { id: "oral-instruments", name: "Oral Instruments", slug: "oral-instruments" },
      { id: "otology", name: "Otology", slug: "otology" },
      { id: "plaster", name: "Plaster", slug: "plaster" },
      { id: "probes-applicators-spatulas", name: "Probes, Applicators & Spatulas", slug: "probes-applicators-spatulas" },
      { id: "rectum", name: "Rectum", slug: "rectum" },
      { id: "retractors-surgical", name: "Retractors", slug: "retractors" },
      { id: "rhinology", name: "Rhinology", slug: "rhinology" },
      { id: "scalpels", name: "Scalpels", slug: "scalpels" },
      { id: "scissors-surgical", name: "Scissors", slug: "scissors" },
      { id: "self-retaining-retractors", name: "Self-Retaining Retractors", slug: "self-retaining-retractors" },
      { id: "sterilization", name: "Sterilization", slug: "sterilization" },
      { id: "suture-surgical", name: "Suture", slug: "suture" },
      { id: "tc-instruments", name: "TC (Tungsten Carbide) Instruments", slug: "tc-tungsten-carbide-instruments" },
      { id: "thoracic-lung-surgery", name: "Thoracic & Lung Surgery", slug: "thoracic-lung-surgery" },
      { id: "tonsil", name: "Tonsil", slug: "tonsil" },
      { id: "towel-tubing-clamps", name: "Towel & Tubing Clamps", slug: "towel-tubing-clamps" },
      { id: "tracheotomy", name: "Tracheotomy", slug: "tracheotomy" },
      { id: "trocars-suction-tubes", name: "Trocars & Suction Tubes", slug: "trocars-suction-tubes" },
      { id: "urology-surgical", name: "Urology", slug: "urology" },
    ]
  },
};

export const MAIN_CATEGORIES = Object.entries(PRODUCT_CATEGORIES).map(([key, value]) => ({
  id: key,
  ...value
}));
